---
title: "Registros de presencia y especies de anfibios de Costa Rica"
author: "Pablo Palacios Díaz - C35849"
format: dashboard
scrolling: True 
httml:
  lang: es
  toc: true
---

```{r}
# Carga de paquetes
library(tidyverse)
library(DT)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leafem)
library(terra)
library(readr)
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis)
```

## Row {height=50%}

```{r}
AEspecies <-
  read_delim(
    file = "especies-anfibios.csv"
    )
  
AEspecies <-
  AEspecies |>
  rename(
    Categoría = iucnRedListCategory,
    Especies = species
  )

```

```{r}
ARegistros <- 
   read_delim(
    file = "registros-anfibios.csv",
    col_select = c("species"),
   )

ARegistros <-
  ARegistros |>
  rename(
    Especies = species
    
  )

```

```{r}
UnionEspecies <-

  left_join(ARegistros, AEspecies,
    by = "Especies"
  )
```

```{r}
#| title: Registros de Presencia de Anfibios

UnionEspecies |>
  datatable(
    options = list(
      pageLength = 10,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

```{r}
#| title: Cantidad de especies por categorías 
barrasEspecies <-
  UnionEspecies |>
  ggplot(aes(x = fct_infreq(Categoría))) +
  geom_bar(
    aes(
      text = paste0(
        "Cantidad de Anfibios: ", after_stat(count)
      )
    ),
  ) +  
  xlab("Categoría") +
  ylab("Cantidad de Anfibios")


ggplotly(barrasEspecies, tooltip = "text") |> 
  config(locale = 'es')
```

```{r}

areas_de_Conservacion <-
  st_read("areas-conservacion.gpkg",
    quiet = TRUE)

areas_de_Conservacion <-
  areas_de_Conservacion |>
  st_transform(4326)

anfibios <-
  st_read(
    "registros-anfibios.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", 
      "Y_POSSIBLE_NAMES=decimalLatitude"   
    ),
    quiet = TRUE
  )

# Asignación del CRS WGS84
st_crs(anfibios) <- 4326
  

```

```{r}
anfibios_union_conserva <-
  st_join(
    x = anfibios,
    y = dplyr::select(areas_de_Conservacion, nombre_ac),
    join = st_within
  )
```

```{r}

riqueza_especies_anfibios <-
  anfibios_union_conserva |>
  st_drop_geometry() |>
  group_by(nombre_ac) |>
  summarize(riqueza_especies = n_distinct(species, na.rm = TRUE))



conserva_union_riqueza <-
  left_join(
    x = areas_de_Conservacion,
    y = dplyr::select(riqueza_especies_anfibios, nombre_ac, riqueza_especies),
    by = "nombre_ac"
  ) |>
  replace_na(list(riqueza_especies = 0))

```

## Row {height=50%}

```{r}
colores_riqueza_especies <-
  colorNumeric(
    palette = "plasma",
    domain = conserva_union_riqueza$riqueza_especies,
    na.color = "transparent"
  )
```
 

```{r}

#| title: Riqueza por Área de Conservación


leaflet() |>
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) |>
  addTiles(group = "Mapa general (OpenStreetMap)") |>
  addProviderTiles(
    providers$Esri.WorldImagery, 
    group = "Imágenes satelitales (ESRI World Imagery)"
  ) |>
addPolygons(
    data = conserva_union_riqueza,
    fillColor = ~ colores_riqueza_especies(conserva_union_riqueza$riqueza_especies),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste("<strong>Área de conservación:</strong>", conserva_union_riqueza$nombre_ac),
      paste("<strong>Riqueza de especies:</strong>", conserva_union_riqueza$riqueza_especies),
      sep = '<br/>')
    ) |>
  addLegend(
    position = "bottomright",
    pal = colores_riqueza_especies,
    values = riqueza_especies_anfibios$riqueza_especies,
    group = "Riqueza de especies",
    title = "Riqueza de especies"
      
  ) |>  
  addLayersControl(
    baseGroups = c(
      "Mapa general (OpenStreetMap)", 
      "Imágenes satelitales (ESRI World Imagery)"
    ),
    overlayGroups = c(
      "Riqueza de especies",
      "Área de coservación"
    )
  ) 
  
```

```{r}
mean_riqueza_conserva <-
  riqueza_especies_anfibios |>
  group_by(nombre_ac) |>
  summarize(riqueza_mean = mean(riqueza_especies))
```

## Row {height=70%}


```{r}
#| title: Riqueza de Anfibios en Áreas de Conservación
barrasRiqueza <-
  mean_riqueza_conserva |>
  ggplot(aes(x = reorder(nombre_ac,-riqueza_mean), y = riqueza_mean )) +
  geom_col(
    aes(
      text = paste0(
        "Riqueza: ", round(after_stat(y),2)
      )
    ),
  ) +  
  xlab("Área de conservación") +
  ylab("Riqueza")


# Gráfico de barras plotly
ggplotly(barrasRiqueza, tooltip = "text") |> 
  config(locale = 'es')
```
